(defun main ()
  (setq n (read))
  (setf a (read))
  (sort a '>)
  (max-triangle a n))

(defun max-triangle (a n)
  (if (> n 2)
	  (progn (setq a1 (car a))
			 (setq a2 (cadr a))
			 (setq a3 (caddr a))
			 (if (> (* a1 a1) (+ (* a2 a2) (* a3 a3)))
				 (max-triangle (cdr a) (- n 1))
				 `(,a1 ,a2 ,a3)))
	  'NO-TRIANGLE-FOUND))
